name: velvetvnaity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
 
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  random_string: ^2.3.1
  
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  flutter_admin_scaffold: ^1.3.0
  shared_preferences: ^2.3.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4

  cached_network_image: ^3.4.0
  firebase_storage: ^12.1.3
  file_picker: ^8.0.7
  video_player: ^2.9.1
  intl: ^0.19.0
 
  





dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
 

flutter:
  uses-material-design: true
  assets:
    - lib/images/Logo/PhotonicFlux_BlackBg_Gif.gif
 
    - assets/images/
    - assets/icon.png
    - lib/images/Photoes/HOME_PAGE_BANNER.gif
    - lib/images/Photoes/Invertertypes_backbanner.jpg
    - lib/images/Photoes/ourmission_backbanner.jpg

  
  
