import 'package:flutter/material.dart';
import 'package:velvetvnaity/Pages/HomePage.dart';
import 'package:velvetvnaity/Pages/CaradPage.dart';
import 'package:velvetvnaity/Pages/ProductPage.dart'; // Import HomePage or the correct page for navigation


class SolarInverter extends StatelessWidget {
  const SolarInverter({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          "Advantages of Solar Inverters",
          style: TextStyle(color: Colors.white),
        ),
        backgroundColor: Colors.black,
        centerTitle: true,
      ),
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
         Color(0xFFA80C0C), // Updated gradient colors
              Colors.black,
            ],
          ),
        ),
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 8.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const SizedBox(height: 20),
         
              const SizedBox(height: 20),
              _buildAdvantageSection(
                title: '1. Improved Efficiency',
                content:
                    'Solar inverters enhance the efficiency of solar panels by converting more of the captured energy into usable electricity. This can lead to higher overall energy production.',
              ),
              const SizedBox(height: 20),
              _buildAdvantageSection(
                title: '2. System Monitoring',
                content:
                    'Many modern solar inverters come with monitoring systems that allow users to track the performance of their solar setup in real-time, ensuring optimal performance.',
              ),
              const SizedBox(height: 20),
              _buildAdvantageSection(
                title: '3. Grid Compatibility',
                content:
                    'Solar inverters ensure that the electricity generated by your solar panels is compatible with the electrical grid, which is crucial for safe and efficient operation.',
              ),
              const SizedBox(height: 20),
              _buildAdvantageSection(
                title: '4. Enhanced Safety Features',
                content:
                    'Advanced solar inverters include safety features that help protect the system from electrical faults and ensure safe operation under various conditions.',
              ),
              const SizedBox(height: 20),
              _buildAdvantageSection(
                title: '5. Support for Energy Storage',
                content:
                    'Some solar inverters support energy storage systems, allowing you to store excess energy for use during non-sunny periods, increasing energy independence.',
              ),
              const SizedBox(height: 20),
              _buildAdvantageSection(
                title: '6. Ease of Installation',
                content:
                    'Modern solar inverters are designed for ease of installation, making it simpler to integrate them with existing solar panel systems.',
              ),
              const SizedBox(height: 20),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => ProductListPage(),
                        ),
                      );
                    },
                    style: ElevatedButton.styleFrom(
                      foregroundColor: Colors.black,
                      backgroundColor: Colors.white,
                      minimumSize: const Size(150, 50),
                    ),
                    child: const Text(
                      'Shop',
                      style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
                    ),
                  ),
                  const SizedBox(width: 20), // Adds spacing between buttons
                  ElevatedButton(
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => const Homepage(), // Ensure this matches the actual class name
                        ),
                      );
                    },
                    style: ElevatedButton.styleFrom(
                      foregroundColor: Colors.black,
                      backgroundColor: Colors.white,
                      minimumSize: const Size(150, 50),
                    ),
                    child: const Text(
                      'Home',
                      style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
                    ),
                  ),
                ],
              ),
              const Padding(
                padding: EdgeInsets.all(16.0),
                child: Center(
                  child: Text(
                    "For more information or if you have any questions, feel free to reach out to us!",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontWeight: FontWeight.w400,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildAdvantageSection({
    required String title,
    required String content,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        const SizedBox(height: 8),
        Text(
          content,
          style: const TextStyle(
            fontSize: 16,
            color: Colors.white,
          ),
        ),
      ],
    );
  }
}
